### ISSUE TITLE
Can't start booking script in advance

### ISSUE THREAD

**Issue by Aleexm** [fistaco/xbook#10]
Running python src/xbook.py --password \<pw\> --booking-category HALL_X3 2024-07-23 18 when said Hall is not yet made available (72hours in advance) returns Could not find a slot starting at 2024-07-23T16:00:00.000Z. Exiting.

I would like to be able to fire up this script whenever, and have it continuously check until the hall becomes available, then book it.

**Comment by fistaco** [comment]
Fixed in 733ea5047b8a86437b8ebf9f7c75bfb43fedbafc and 3399cbf4ef4f53eadb421b2878efe55b3aaf221d.
